server:
  port: 9000


spring:
  application:
    name: auth-server
  datasource:
    druid:
      url: jdbc:mysql://111.231.110.198:3306/platform?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: _Lyj112233
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙 slf4j日志用的filter
      filters: stat,wall,slf4j
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.jihe.auth.*
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: aaa
        login-password: aaa
        # 外部访问IP白名单
        allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        #deny: 172.18.1.252
      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

  jpa:
    show-sql: true
  redis:
    database: 0
    host: 111.231.110.198
    password: 123456
    port: 6379
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848