
server:
  port: 9999

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: web-manager
        uri: http://localhost:8082
        predicates:
        - Path=/web/**
        filters:
        - StripPrefix=1
      - id: service-order
        uri: http://localhost:8083
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848